update BR with cleanbuild
likely the deps should be filled in appropriate -devel packages instead, not here

and some dep still missing:
error: File not found: /usr/src/BUILD/kp5-breeze-5.4.0-root-builder/usr/bin/breeze-settings5
error: File not found: /usr/src/BUILD/kp5-breeze-5.4.0-root-builder/usr/share/icons/hicolor/scalable/apps/breeze-settings.svgz